obj-$(CONFIG_VIDEO_NXP_CAPTURE) += nxp-capture.o nxp-vin-clipper.o
obj-$(CONFIG_NXP_CAPTURE_DECIMATOR) += nxp-decimator.o
obj-$(CONFIG_NXP_CAPTURE_MIPI_CSI)  += nxp-csi.o
obj-$(CONFIG_LOOPBACK_SENSOR_DRIVER) += loopback-sensor.o

EXTRA_CFLAGS += -Idrivers/media/platform/nexell
EXTRA_CFLAGS += -Idrivers/platform/nexell/s5p6818/prototype/module
