#
# Copyright 2009 Nexell Co.
#	http://www.nexell.co.kr
#
obj-y += soc-reset.o soc-gpio.o

obj-$(CONFIG_NXP_DISPLAY)       += display.o
obj-$(CONFIG_NXP_DISPLAY_LCD)   += display_lcd.o
obj-$(CONFIG_NXP_DISPLAY_LVDS)  += display_lvds.o
obj-$(CONFIG_NXP_DISPLAY_HDMI)  += display_hdmi.o hdmi/
obj-$(CONFIG_NXP_DISPLAY_MIPI)  += display_mipi.o
obj-$(CONFIG_NXP_DISPLAY_RESC)  += display_resc.o
obj-$(CONFIG_NXP_OUT_HDMI)      += hdmi/

